/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_ndktest_NdkJniTest.h>
/* Header for class com_ndktest_NdkJniTest */

#ifndef _Included_com_ndktest_NdkJniTest
#define _Included_com_ndktest_NdkJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndktest_NdkJniTest
 * Method:    myNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndktest_NdkJniTest_myNDK
  (JNIEnv *env, jobject obj){
  return (*env)->NewStringUTF(env, "This just a test for Android Studio NDK JNI developer!");
  }

#ifdef __cplusplus
}
#endif
#endif
